### ISSUE TITLE
Suggestion: Option for a %chance to lower the number available by a factor

### ISSUE THREAD

**Issue by Clock-name** [DarkKronicle/CommandPotential#4]
ETC:

command potential for white items option: 6

percent chance to lower 0.4

factor to lower: 0.5

40% of the time you only get 3 options, you can expand on this if you wish i only suggest it so i could do 2 and sometimes get 1.

Or, if you want simplicity, just a %chance to drop the first item in the potential list. (would be great so you cant cheese things with scrappers too, some sorta scrap blacklist)

**Comment by DarkKronicle** [comment]
This would be really cool. I’ll try adding it.

**Comment by DarkKronicle** [comment]
Added 
![image](https://user-images.githubusercontent.com/38167691/158080986-cd5b6a1f-cf8a-4808-80ed-d571c24f24f9.png)

**Comment by Clock-name** [comment]
Thanks, this is even more based then what i described, you went above and beyond and made quite possibly the best mod on the thunderstore that i will never go without again.

Can you do silly things like 0.01% chance for 20 items being pickable or just full numbers or make it effected by the luck stat?
