### ISSUE TITLE
Artifact of Command not working with mod

### ISSUE THREAD

**Issue by LeonMelowen** [DarkKronicle/CommandPotential#5]
The "Artifact of Command" has for some reason the choising disabled its like not having it active.

**Comment by DarkKronicle** [comment]
Oh shoot I know exactly what causes this

**Comment by DarkKronicle** [comment]
I can’t fix it right now, but hopefully by tonight https://github.com/DarkKronicle/CommandPotential/blob/main/CommandPotential/CommandPotential.cs#L138

**Comment by LeonMelowen** [comment]
Ok thanks!

**Comment by DarkKronicle** [comment]
Fixed now
