### ISSUE TITLE
Suggestion: Make printers like scrappers

### ISSUE THREAD

**Issue by NighttimeWorker** [DarkKronicle/CommandPotential#7]
First love the mod, having it as its own artifact is awesome and the customizability is great.

In 1.3.2 You made scrappers only output scrap, Would you be able to do the same thing for printers? Currently it makes printers (especially if theres a scrapper) op in my opinion rerolling until it gives what you want.

**Comment by DarkKronicle** [comment]
I agree completely! The problem is is there is no way to tell if an item came from a printer. You can disable printers from spawning. I really wish this was easy.

**Comment by NighttimeWorker** [comment]
Alright, was just a thought.

**Comment by NighttimeWorker** [comment]
Sharesuite has different behavior for printers/cauldrons and they appear to use RoR2.CostTypeIndex to do it. Would you be able to use that too? It wouldn't be specific for printers but only printers and cauldrons cost and drop items that I can think of.

**Comment by DarkKronicle** [comment]
Oh my gosh that's genius

**Comment by DarkKronicle** [comment]
I DID IT!
